package com.twu.biblioteca.constants;

public enum UIEnum {
    WELCOME_MESSAGE, OPTION_LIST, OPTION_INVALID,
    CHECKOUT_SUCCESS, CHECKOUT_FAIL, RETURN_SUCCESS, RETURN_FAIL, USER_INPUT, USER_INPUT_ITEM,
    NOT_LOGGED_IN, ALREADY_LOGGED_IN, WRONG_OWNER, INVALID_CREDENTIALS, WHOAMI, INVALID_USER
}
